% kb_aug.pl (auto-generated WordNet augmentation)
% Provides: synonym/2, is_a/2
synonym(privacy, privacy).
synonym(privacy, privateness).
synonym(privacy, seclusion).
is_a(privacy, reclusiveness).
synonym(policy, policy).
is_a(policy, plan_of_action).
synonym(explain, explain).
synonym(explain, explicate).
is_a(explain, inform).
synonym(information, information).
synonym(information, info).
is_a(information, message).
synonym(google, google).
synonym(collect, collect).
synonym(collect, take_in).
is_a(collect, take).
synonym(use, use).
synonym(use, utilize).
synonym(use, utilise).
synonym(use, apply).
synonym(use, employ).
synonym(service, service).
is_a(service, work).
synonym(data, data).
synonym(data, information).
is_a(data, collection).
synonym(vary, change).
synonym(vary, alter).
synonym(vary, vary).
synonym(control, control).
is_a(control, activity).
synonym(choose, choose).
synonym(choose, take).
synonym(choose, select).
synonym(choose, pick_out).
is_a(choose, decide).
synonym(sign, sign).
synonym(sign, subscribe).
is_a(sign, write).
synonym(store, store).
synonym(store, hive_away).
synonym(store, lay_in).
synonym(store, put_in).
synonym(store, salt_away).
synonym(store, stack_away).
synonym(store, stash_away).
is_a(store, keep).
synonym(identifier, identifier).
is_a(identifier, symbol).
synonym(associate, associate).
synonym(associate, tie_in).
synonym(associate, relate).
synonym(associate, link).
synonym(associate, colligate).
synonym(associate, link_up).
synonym(associate, connect).
is_a(associate, think).
synonym(browser, browser).
is_a(browser, spectator).
synonym(device, device).
is_a(device, instrumentality).
synonym(maintain, keep).
synonym(maintain, maintain).
synonym(maintain, hold).
synonym(preference, preference).
synonym(preference, penchant).
synonym(preference, predilection).
synonym(preference, taste).
is_a(preference, liking).
synonym(session, session).
is_a(session, meeting).
synonym(create, make).
synonym(create, create).
synonym(account, account).
synonym(account, business_relationship).
is_a(account, relationship).
synonym(provide, supply).
synonym(provide, provide).
synonym(provide, render).
synonym(provide, furnish).
is_a(provide, give).
synonym(personal, personal).
synonym(name, name).
is_a(name, language_unit).
synonym(password, password).
synonym(password, watchword).
synonym(password, word).
synonym(password, parole).
synonym(password, countersign).
is_a(password, positive_identification).
is_a(password, secret).
synonym(add, add).
is_a(add, increase).
synonym(detail, detail).
synonym(detail, item).
synonym(detail, point).
is_a(detail, fact).
synonym(phone, telephone).
synonym(phone, phone).
synonym(phone, telephone_set).
is_a(phone, electronic_equipment).
synonym(number, number).
synonym(number, figure).
is_a(number, amount).
synonym(payment, payment).
synonym(payment, defrayal).
synonym(payment, defrayment).
is_a(payment, commerce).
synonym(content, content).
is_a(content, collection).
synonym(upload, upload).
is_a(upload, transfer).
synonym(receive, receive).
synonym(receive, have).
is_a(receive, get).
synonym(email, electronic_mail).
synonym(email, e_mail).
synonym(email, email).
is_a(email, electronic_communication).
synonym(photo, photograph).
synonym(photo, photo).
synonym(photo, exposure).
synonym(photo, picture).
synonym(photo, pic).
is_a(photo, representation).
synonym(document, document).
synonym(document, written_document).
synonym(document, papers).
is_a(document, writing).
synonym(comment, remark).
synonym(comment, comment).
synonym(comment, input).
is_a(comment, statement).
synonym(technical, technical).
synonym(interaction, interaction).
is_a(interaction, action).
synonym(address, address).
synonym(address, computer_address).
synonym(address, reference).
is_a(address, code).
synonym(date, date).
synonym(date, day_of_the_month).
is_a(date, day).
synonym(time, time).
synonym(time, clip).
is_a(time, case).
synonym(url, url).
synonym(url, uniform_resource_locator).
synonym(url, universal_resource_locator).
is_a(url, address).
synonym(technology, technology).
synonym(technology, engineering).
is_a(technology, application).
is_a(technology, profession).
synonym(cookie, cookie).
synonym(cookie, cooky).
synonym(cookie, biscuit).
is_a(cookie, cake).
synonym(log, log).
is_a(log, wood).
synonym(deliver, deliver).
is_a(deliver, bring).
synonym(keep, continue).
synonym(keep, go_on).
synonym(keep, proceed).
synonym(keep, go_along).
synonym(keep, keep).
is_a(keep, act).
synonym(work, function).
synonym(work, work).
synonym(work, operate).
synonym(work, go).
synonym(work, run).
synonym(improve, better).
synonym(improve, improve).
synonym(improve, amend).
synonym(improve, ameliorate).
synonym(improve, meliorate).
is_a(improve, change).
synonym(develop, develop).
is_a(develop, create).
synonym(feature, feature).
synonym(feature, characteristic).
is_a(feature, property).
synonym(personalize, personalize).
synonym(personalize, personalise).
synonym(personalize, individualize).
synonym(personalize, individualise).
is_a(personalize, change).
synonym(ad, ad).
synonym(ad, advertisement).
synonym(ad, advertizement).
synonym(ad, advertising).
synonym(ad, advertizing).
synonym(ad, advert).
is_a(ad, promotion).
synonym(depend, depend).
is_a(depend, be).
synonym(setting, setting).
synonym(setting, background).
synonym(setting, scope).
is_a(setting, environment).
synonym(communicate, communicate).
synonym(communicate, pass_on).
synonym(communicate, pass).
synonym(communicate, pass_along).
synonym(communicate, put_across).
is_a(communicate, convey).
synonym(user, user).
is_a(user, person).
synonym(protect, protect).
is_a(protect, defend).
synonym(fraud, fraud).
is_a(fraud, crime).
synonym(abuse, maltreatment).
synonym(abuse, ill_treatment).
synonym(abuse, ill_usage).
synonym(abuse, abuse).
is_a(abuse, mistreatment).
synonym(security, security).
is_a(security, safety).
synonym(risk, hazard).
synonym(risk, jeopardy).
synonym(risk, peril).
synonym(risk, risk).
synonym(risk, endangerment).
is_a(risk, danger).
synonym(allow, let).
synonym(allow, allow).
synonym(allow, permit).
synonym(share, share).
is_a(share, use).
synonym(publicly, publicly).
synonym(publicly, publically).
synonym(publicly, in_public).
synonym(privately, privately).
synonym(privately, in_private).
synonym(privately, in_camera).
synonym(accessible, accessible).
synonym(search, search).
synonym(search, hunt).
synonym(search, hunting).
is_a(search, activity).
synonym(engine, engine).
is_a(engine, motor).
synonym(retain, retain).
is_a(retain, hold).
synonym(kind, kind).
synonym(kind, sort).
synonym(kind, form).
synonym(kind, variety).
is_a(kind, category).
synonym(period, time_period).
synonym(period, period_of_time).
synonym(period, period).
is_a(period, fundamental_quantity).
synonym(option, option).
is_a(option, derivative_instrument).
synonym(delete, delete).
synonym(delete, cancel).
is_a(delete, remove).
synonym(legal, legal).
synonym(need, need).
synonym(need, demand).
is_a(need, condition).
synonym(business, business).
synonym(business, concern).
synonym(business, business_concern).
synonym(business, business_organization).
synonym(business, business_organisation).
is_a(business, enterprise).
